// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbhzlmxjffquomqfceme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiaHpsbXhqZmZxdW9tcWZjZW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTgwNjAsImV4cCI6MjA2MzgzNDA2MH0.5v89J0teAglYi4h1VW5h8HXjNZ_DUKh7dRqvWijU62o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);